# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireLampades' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseCore', '~> 3.4'

  target 'FireLampadesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
