# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireLampades' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseCore', '~> 3.4'
  pod 'Swinject', '2.0.0'
  pod 'SwinjectStoryboard', '1.0.0'
  pod 'AnimatedTextInput', '~> 0.3.0'

  target 'FireLampadesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
